### ISSUE TITLE
Hidden column

### ISSUE THREAD

**Issue by promogest** [markcell/jQuery-Tabledit#2]
I have another problem because table index is not always my id. I can put the value in a coliumn and hidden with 
$('#table tr *:nth-child(5)').css('display','none');
but i am not able to receive the value server side. 
ImmutableMultiDict([('action', u'edit'), ('index', u'1'), ('denominazione', u'wwALTRO'), ('denominazione_breve', u'ALTRO')]))
index is what iis "id" in your examples and denominazione and denominazione are the two visible column. there is a third column " id" hidden. 
Thanks

**Comment by markcell** [comment]
If I have understood correctly, you can use "hideIdentifier" option, which hides the column that stores each row identifier.

```js
$('#table').Tabledit({
  url: 'example.php',
  hideIdentifier: true,
  columns: {
    // Column used to identify table row.
    // [column_index, input_name]
    identifier: [0, 'id'],
    // Columns to transform in editable cells.
    // [[column_index, input_name], [column_index, input_name, select_options]]
    editable: [[1, 'car'], [2, 'color', '{"1": "Red", "2": "Green", "3": "Blue"}']]
  }
});
```
Notes:
1. Is not necessary to be "id" the name given to the input identifier.
2. Each editable column has an input, and a span that is toggled as view mode or edit mode. 
3. Only editable columns and the identifier column (<input type = "hidden">) is that they are sent to the server, because they are the ones that have form inputs.

**Comment by promogest** [comment]
hideIdentifier: true   did the trick!
i used the first column filled with the real id of the data and this option hide it. 
thanks!
